### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ardswebdesign** [dgrundel/woo-product-importer#117]
Hi

I have just installed this plugin but when I go to import the products nothing is happening, please see attached screenshot so you can see what I mean.

Cheers
Richard
![error](https://cloud.githubusercontent.com/assets/15280475/10711649/dc3062ec-7a79-11e5-89aa-5c009c3bd083.jpg)

**Comment by ardswebdesign** [comment]
Hi

Sorry I have just saw the updated version of this plugin and I have installed it and its working. 

Thanks, Great Plugin.

Richard

**Comment by RKKDDANG** [comment]
Hi

can u  plz  let me know wher did u got updated version 

and you plz share it

email : indiansfashion@gmail.com

thanks
