### ISSUE TITLE
Fatal error While importing

### ISSUE THREAD

**Issue by krshnkrishna** [dgrundel/woo-product-importer#126]
Fatal error: Call to undefined method WooCommerce::get_attribute_taxonomies() in /home/bullsbike/public_html/wp-content/plugins/woo-product-importer-master/woo-product-importer-ajax.php on line 85

**Comment by sebaswelt** [comment]
Change line 85 to:  $attribute_taxonomies = wc_get_attribute_taxonomies();

**Comment by RKKDDANG** [comment]
Same problem here
plz help us i tried lots time but still its not working not importing any product
any one have other option or updated plugin plz send us

thanks
indiansfashion@gmail.com

**Comment by sebaswelt** [comment]
Change line 85 in woo-product-importer-ajax.php to: $attribute_taxonomies = wc_get_attribute_taxonomies();
